apiVersion: v1
kind: Secret
metadata:
 name: jfrogcred
 namespace: mavine

data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJtYXZpbmUwMDEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHbDJhVzVsTG5SaGJXbHVZVzVuUUdodmJXVnZabVpwWTJVdVoyOTJMblZyT2t0cGJtY3hNVEV4IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
